### ISSUE TITLE
Inner Exception not shown

### ISSUE THREAD

**Issue by MhozaifaA** [OsamaAlRashed/EasyRefreshToken#1]
face exception when I try to call  `TokenService.Clear()` API,  

**System.Exception  message "An error occurred while removing the entries. See the inner exception for details"**

I don't know why , but after check I recognized I don't have permission to use `Delete `statement as "limited User" not "Admin" in SQLDB

So please can support to see inner exceptions or any idea

### Suggestion
I check source code, 
https://github.com/OsamaAlRashed/EasyRefreshToken/blob/9a3436b752501c22a2a71ec1d979dcc785e559c4/EasyRefreshToken/TokenService/TokenService.cs#L95

I see here not correct to handle exception,  I think easy to solve by throw correct Exception As:

``` C#

 catch (Exception ex) {
     throw ex;
}

//or 

 catch (Exception ex){
     throw;
}
```

I  notice same issue in  `Add(), Delete(), Clear()` APIs

**Comment by OsamaAlRashed** [comment]
I fixed it, all thanks ..
