### ISSUE TITLE
Failed to refresh token while sending in querystring

### ISSUE THREAD

**Issue by Joudy-Dabbit** [OsamaAlRashed/EasyRefreshToken#5]
I was trying to send a token in the query, but that failed
So when I read the code, I found that the function that generates the refresh token, it generates letters, numbers, symbols... including the "+"
But "+" doesn't send
Instead, replace it with a blank
So it failed and can't recognize him..

**Comment by OsamaAlRashed** [comment]
@Joudy-Dabbit  
Hi Joudy, you can encode URL, that will solve the problem.
please see [Query String](https://en.wikipedia.org/wiki/Query_string#URL_encoding)
Although I will fix it in the next version.
Thanks.

**Comment by Joudy-Dabbit** [comment]
@OsamaAlRashed 
I read it, Thanks.
